src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 * @UniqueEntity(
 *     fields={"name", "surname", "patronymic"},
 *     message="This author already exists"
 * )
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $patronymic;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Book", mappedBy="authors")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = mb_convert_case($name, MB_CASE_TITLE);

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = mb_convert_case($surname, MB_CASE_TITLE);

        return $this;
    }

    public function getPatronymic(): ?string
    {
        return $this->patronymic;
    }

    public function setPatronymic(string $patronymic): self
    {
        $this->patronymic = mb_convert_case($patronymic, MB_CASE_TITLE);

        return $this;
    }

    public function getShortName(): ?string
    {
        return sprintf('%s %s.%s.', $this->getSurname(), mb_substr($this->getName(), 0, 1), mb_substr($this->getPatronymic(), 0, 1));
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            $book->removeAuthor($this);
        }

        return $this;
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class AuthorType
 * @package App\Form
 */
class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('surname')
            ->add('patronymic')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Entity\Author;
use App\Form\AuthorType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class AuthorController extends AbstractController
{
    /**
     * @Route("/authors", name="authors")
     */
    public function index()
    {
        $authors = $this->getDoctrine()->getRepository(Author::class)->findAll();

        return $this->render('author/index.html.twig', [
            'authors' => $authors
        ]);
    }

    /**
     * @Route("/author/create", name="author_create")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function create(Request $request)
    {
        $author = new Author();
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($author);
            $entityManager->flush();

            return $this->redirectToRoute('authors');
        }

        return $this->render('author/create.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/author/{id<\d+>}/edit", name="author_edit")
     * @param Request $request
     * @param Author $author
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Author $author)
    {
        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($author);
            $entityManager->flush();

            return $this->redirectToRoute('authors');
        }
        return $this->render('author/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/author/{id<\d+>}/delete", name="author_delete")
     * @param Author $author
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function delete(Author $author)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($author);
        $entityManager->flush();
        return $this->redirectToRoute('authors');
    }
}

templates/author/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding author{% endblock %}

{% block body %}
    <h1>New author</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('authors') }}">authors</a>
    <a href="{{ path('books') }}">books</a>
    <hr>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" class="btn" value="Create" />
    {{ form_end(form) }}
{% endblock %}

templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editing {{ form.vars.data.shortName }}!{% endblock %}

{% block body %}
    <h1>{{ form.vars.data.shortName }}</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('authors') }}">authors</a>
    <a href="{{ path('books') }}">books</a>
    <hr>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Save" />
    {{ form_end(form) }}
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Authors{% endblock %}

{% block body %}
    <h1>Authors</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('books') }}">books</a>
    <hr>
    <table>
        <th>name</th>
        {% for author in authors %}
            <tr>
                <td>{{ author.id }}</td>
                <td>{{ author.shortName }}</td>
                <td>
                    <a href="{{ path('author_edit', {'id': author.id}) }}">edit</a>
                </td>
                <td>
                    <a href="{{ path('author_delete', {'id': author.id}) }}">delete</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <hr>
    <a href="{{ path('author_create') }}">create</a>
{% endblock %}