src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 * @UniqueEntity(
 *     fields={"name", "surname", "patronymic"},
 *     message="This author already exists"
 * )
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $patronymic;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Book", mappedBy="authors")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = mb_convert_case($name, MB_CASE_TITLE);

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = mb_convert_case($surname, MB_CASE_TITLE);

        return $this;
    }

    public function getPatronymic(): ?string
    {
        return $this->patronymic;
    }

    public function setPatronymic(string $patronymic): self
    {
        $this->patronymic = mb_convert_case($patronymic, MB_CASE_TITLE);

        return $this;
    }

    public function getShortName(): ?string
    {
        return sprintf('%s %s.%s.', $this->getSurname(), mb_substr($this->getName(), 0, 1), mb_substr($this->getPatronymic(), 0, 1));
    }

    /**
     * @return Collection|Book[]
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->contains($book)) {
            $this->books->removeElement($book);
            $book->removeAuthor($this);
        }

        return $this;
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 * @UniqueEntity("isbn")
 * @UniqueEntity(
 *     fields={"name", "year"},
 *     message="This book with that name and year already exists"
 * )
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="smallint")
     */
    private $year;

    /**
     * @ORM\Column(type="bigint", unique=true)
     */
    private $isbn;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Author", inversedBy="books")
     */
    private $authors;

    /**
     * @ORM\Column(type="smallint")
     */
    private $pages_count;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(
     *     mimeTypes = {"image/png", "image/jpeg"},
     *     mimeTypesMessage = "Only jpeg or png image allowed"
     * )
     */
    private $cover;

    public function __construct()
    {
        $this->authors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getIsbn(): ?int
    {
        return $this->isbn;
    }

    public function setIsbn(int $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    /**
     * @return Collection|Author[]
     */
    public function getAuthors(): Collection
    {
        return $this->authors;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->authors->contains($author)) {
            $this->authors[] = $author;
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        if ($this->authors->contains($author)) {
            $this->authors->removeElement($author);
        }

        return $this;
    }

    public function getPagesCount(): ?int
    {
        return $this->pages_count;
    }

    public function setPagesCount(int $pages_count): self
    {
        $this->pages_count = $pages_count;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover($cover): self
    {
        $this->cover = $cover;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class BookType
 * @package App\Form
 */
class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('year')
            ->add('isbn')
            ->add('pages_count')
            ->add('authors', EntityType::class, [
                'class' => Author::class,
                'choice_label' => 'shortName',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('cover', FileType::class, [
                'help' => 'jpeg or png image',
                'required' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BookController
 */
class BookController extends AbstractController
{
    /**
     * @Route("/books", name="books")
     */
    public function index()
    {
        $books = $this->getDoctrine()->getRepository(Book::class)->findAll();

        return $this->render('book/index.html.twig', [
            'books' => $books
        ]);
    }

    /**
     * @Route("/book/{id<\d+>}", name="book")
     * @param Book $book
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(Book $book)
    {
        return $this->render('book/show.html.twig', [
            'book' => $book, 'file' => new File($this->getParameter('covers_directory') . '/' . $book->getCover())
        ]);
    }

    /**
     * @Route("/book/create", name="book_create")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function create(Request $request)
    {
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($book);
            $entityManager->flush();

            return $this->redirectToRoute('book', ['id' => $book->getId()]);
        }

        return $this->render('book/create.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/book/{id<\d+>}/edit", name="book_edit")
     * @param Request $request
     * @param Book $book
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function edit(Request $request, Book $book)
    {
        if ($book->getCover()) {
            $book->setCover(
                new File($this->getParameter('covers_directory') . '/' . $book->getCover())
            );
        }

        $form = $this->createForm(BookType::class, $book);
        $form->handleRequest($request);

        if (!$form->isSubmitted() || !$form->isValid()) {
            return $this->render('book/edit.html.twig', [
                'form' => $form->createView()
            ]);
        }

        $coverFile = $form->get('cover')->getData();

        if ($coverFile instanceof UploadedFile) {
            $coverName = $book->getId() . $book->getName() . '_cover.' . $coverFile->guessExtension() ?? 'bin';
            $coverFile->move(
                $this->getParameter('covers_directory'),
                $coverName
            );
            $book->setCover($coverName);
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($book);
        $entityManager->flush();

        return $this->redirectToRoute('book', ['id' => $book->getId()]);
    }

    /**
     * @Route("/book/{id<\d+>}/delete", name="book_delete")
     * @param Book $book
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function delete(Book $book)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($book);
        $entityManager->flush();
        return $this->redirectToRoute('books');
    }
}

templates/book/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding book{% endblock %}

{% block body %}
    <h1>New book</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('books') }}">books</a>
    <a href="{{ path('authors') }}">authors</a>
    <hr>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" class="btn" value="Create" />
    {{ form_end(form) }}
{% endblock %}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editing {{ form.vars.data.name }}!{% endblock %}

{% block body %}
    <h1>{{ form.vars.data.name }}</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('books') }}">books</a>
    <a href="{{ path('authors') }}">authors</a>
    <a href="{{ path('book', {'id': form.vars.data.id}) }}">back</a>
    <hr>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="Save" />
    {{ form_end(form) }}
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books list{% endblock %}

{% block body %}
    <h1>Books list</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('authors') }}">authors</a>
    <hr>
    <table>
        <th>name</th>
        {% for book in books %}
            <tr>
                <td>
                    <a href="{{ path('book', {'id': book.id}) }}">{{ book.name }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
    <hr>
    <a href="{{ path('book_create') }}">create</a>
{% endblock %}

templates/book/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book: {{ book.name }}!{% endblock %}

{% block body %}
    <h1>{{ book.name }}</h1>
    <hr>
    <a href="{{ path('welcome') }}">home</a>
    <a href="{{ path('books') }}">books</a>
    <a href="{{ path('authors') }}">authors</a>
    <hr>
{{ dump() }}
    <table>
        <th>id</th>
        <th>name</th>
        <th>year</th>
        <th>isbn</th>
        <th>pages</th>
        <th>cover</th>
        <th>authors</th>
        <tr>
            <td>{{ book.id }}</td>
            <td>{{ book.name }}</td>
            <td>{{ book.year }}</td>
            <td>{{ book.isbn }}</td>
            <td>{{ book.pagesCount }}</td>
            <td>{{ book.cover }}</td>
            <td>
                {% for author in book.getAuthors %}
                {{ author.shortName }}<br>
                {% endfor %}
            </td>
        </tr>
    </table>

    <hr>
    <a href="{{ path('book_edit', {'id': book.id}) }}">edit</a>
    <a href="{{ path('book_delete', {'id': book.id}) }}">delete</a>
{% endblock %}